name: Build

on: [push, pull_request]

jobs:
  windows:
    name: Build (${{ matrix.os }} - ${{ matrix.type }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2022, windows-2019]
        type: [Debug, Release]
        exception: [No-Exceptions, C++-Exceptions, structured-Exceptions]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - if: matrix.exception == 'No-Exceptions'
        name: Configure
        run: cmake -S . -B build
      - if: matrix.exception == 'C++-Exceptions'
        name: Configure
        run: cmake -S . -B build -DPTHREADS4W_BUILD_C=FALSE -DPTHREADS4W_BUILD_CE=TRUE
      - if: matrix.exception == 'structured-Exceptions'
        name: Configure
        run: cmake -S . -B build -DPTHREADS4W_BUILD_C=FALSE -DPTHREADS4W_BUILD_SE=TRUE
      - name: Build ${{ matrix.type }}
        run: cmake --build build --config ${{ matrix.type }}
      - name: Test ${{ matrix.type }}
        run: |
          cd build
          ctest -C ${{ matrix.type }}
